// <auto-generated />
using System;
using Covid19CroatiaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Covid19CroatiaAPI.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210501205901_InitalCreate")]
    partial class InitalCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Covid19CroatiaAPI.Entities.DailyCovidOverview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DailyNewConfirmed")
                        .HasColumnType("int");

                    b.Property<int>("DailyNewDeaths")
                        .HasColumnType("int");

                    b.Property<int>("DailyNewRecovered")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalConfirmed")
                        .HasColumnType("int");

                    b.Property<int>("TotalDeaths")
                        .HasColumnType("int");

                    b.Property<int>("TotalRecovered")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DailyCovidOverviews");
                });
#pragma warning restore 612, 618
        }
    }
}
